# Open a browser in the URL http://localhost:8000 to see the app
# In another terminal, use the following to run `php artisan` commands:
# $ podman compose exec app sh
version: "3"
services:
  app:
    image: localhost/agora_app:latest
    environment:
      APP_ENV: production
      APP_DEBUG: false
      IN_PRODUCTION: true
    depends_on:
      database:
          condition: service_healthy
      mailpit:
          condition: service_started
      pdf-converter:
          condition: service_started
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/app
    networks:
      - app-network

  database:
    image: mariadb:lts-ubi
    environment:
      # Loaded automatically from the .env file
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - production-database-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

  mailpit:
    image: axllent/mailpit:v1.29
    # 1025 is automatically routed
    ports:
      - "8025:8025"
    networks:
      - app-network

  pdf-converter:
    image: ghcr.io/acsone/kwkhtmltopdf/0.12.6.1:1.1.0
    # Port 8080 automatically routed
    networks:
      - app-network

networks:
  app-network:
volumes:
  production-database-data:
